version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bonus_system_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: bonus_user
      POSTGRES_PASSWORD: bonus_password
      POSTGRES_DB: bonus_system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - bonus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bonus_user -d bonus_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bonus_system_redis_dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - bonus_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bonus_system_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bonus_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: bonus_system_redis_commander_dev
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - bonus_network

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  bonus_network:
    driver: bridge
