#
# @file: docker-compose.yml
# @description: Local Dev stack for Postgres & Redis (Windows-friendly)
# @project: SaaS Bonus System
# @dependencies: Docker, Docker Compose v2
# @created: 2025-09-06
# @author: AI Assistant + User

services:
  postgres:
    image: postgres:17
    container_name: saas-postgres
    restart: unless-stopped
    ports:
      - "5434:5432" # host:container (5432 занят локальным сервисом)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_bonus_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: saas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:


