version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bonus-system-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bonus_user
      POSTGRES_PASSWORD: bonus_password
      POSTGRES_DB: bonus_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bonus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bonus_user -d bonus_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: bonus-system-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bonus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Commander (GUI for Redis) - Development only
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: bonus-system-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - bonus-network
    depends_on:
      - redis
    profiles:
      - dev

  # pgAdmin (GUI for PostgreSQL) - Development only
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bonus-system-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - bonus-network
    depends_on:
      - postgres
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  bonus-network:
    driver: bridge